### ISSUE TITLE
Improved cell morphologies in miniapp

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#107]
Currently the miniapp uses cells with a very simple, and quite unrealistic, morphology. Some parts of the application performance can be very sensitive to cell morphology (in particular the solution of Hines matrices on the GPU).

This task will add support in the miniapp command line interface and the cell recipes for specifying the following:
* __cell morphology__: number of branches, depth of the tree, and number of compartments per segment.
* __cell-cell variability__: in real models each individual cell can have different morphologies. Simple control for the level of variability between cell morphologies should be provided.

**Comment by halfflat** [comment]
This has been partially addressed by PR #162 — the PR adds a `morphology_pool` from which cell morphologies are drawn in the recipes, and allows loading SWC files to fill the pool.

A more complete solution would allow other parametric descriptions, e.g. directly from the L-system generator, or parameterized simple trees.

Proposed continuation of this task:
1. Allow pool to be initially filled via a parametric description, rather than just via SWC loading.
2. Avoid the necessity of pre-computing the morphologies by replacing the existing `morphology_pool` with an interface that can be specialized to provide the morphologies on demand, given an index and parametric description.

**Comment by halfflat** [comment]
As the miniapp is going away (see issue #693), consider making the morphology pool code part of the Arbor library.
