### ISSUE TITLE
[Question] Allen model from CNS 2020 presentation

### ISSUE THREAD

**Issue by pramodk** [arbor-sim/arbor#1097]
Hello Ben,

Thanks for nice talk which described portability challenges both from specification perspective as well as performance.

I would like to closely look at NEURON performance for the model you mentioned : http://celltypes.brain-map.org/experiment/electrophysiology/488683425

I see that the download file format is NWB. If you have setup NEURON simulator already to run this model, may be taking a modified tarball from you would be easier to reproduce the results? Obviously if there are no restrictions to share such model with modifications.

Thank you!

**Comment by bcumming** [comment]
On that page, there is a drop down box titled `Select neuronal model` above the plots. Select `Biophysical - all active`.

Then below that there is a link for `Download Model`, which is a zip file with the SWC file, NMODL mechanisms, JSON file in a format that closely resembles SONATA, and the NWB file with the experimental data.

Alternatively, you can download the model using the Allen SDK Python interface.

We tried running the model directly in Allen SDK, but there were problems that I don't think were addressed:
https://github.com/AllenInstitute/AllenSDK/issues/1596

We cleaned up the NMODL files, performing some basic inlining and removing all of the `vtrap` `if-else` patterns  with out `exprelr` expressions (which you should consider adding to NMODL!)
https://github.com/arbor-sim/arbor/tree/master/mechanisms/allen

**Comment by pramodk** [comment]
Thanks lot for pointing out the upstream issue! I am also now stuck at:

```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'sweeps_by_type'
```


> removing all of the vtrap if-else patterns with out exprelr expressions

Ahh...`vtrap` is classic one, thanks for pointing that! I wanted to handle that as AST pattern matching and re-writing expression rather than updating mod file manually. (lets see...I will take a look when time permits)

**Comment by bcumming** [comment]
I would be careful about manipulating the AST in that case, because:
* you are rewriting the original code to have a different meaning, and numerically different results around `x=0`.
* the `vtrap` pattern is implemented in quite a few different ways that would be very hard to detect looking at the AST.

If you add an `exprelr` or `exmp1` for direct use in the NMODL code, you could detect harmful `vtrap` patterns and print a warning, with a pointer to how to fix the code.

`expm1` is provided by most math/SIMD libraries. Here are the docs for how we implement it:
https://arbor.readthedocs.io/en/latest/simd_api.html#operatorname-expm1-x

And below that are the docs that show how we use it to construct `exprelr`.

**Comment by pramodk** [comment]
thanks Ben for additional reference and pointers! I will come back here in case of further clarification.

As I have necessary information and issue is pending [upstream](https://github.com/AllenInstitute/AllenSDK/issues/1596#issuecomment-662133279), we can close this issue.
