### ISSUE TITLE
Different CV areas using equivalent trees 

### ISSUE THREAD

**Issue by noraabiakar** [arbor-sim/arbor#1284]
DIfferent CV areas are generated starting from 2 seemingly equivalent morphologies and discretisations (1 CV total for both morphologies)

**Morphology 1**

1. cables:
```
(segment 0 (point -6.3 0 0 6.3) (point 6.3 0 0 6.3) 1)
(segment 1 (point 6.3 0 0 0.5) (point 206.3 0 0 0.2) 3)
```
2. CV area = `938.583` (this is the correct answer = (2 * π * 6.3 * 12.6) + (2 * π * ((0.5+0.2)/2) * 200) )

**Morphology 2**
1. cables: 
```
(segment 0 (point -6.3 0 0 6.3) (point 6.3 0 0 6.3) 1)
(segment 1 (point 6.3 0 0 6.3) (point 6.3 0 0 0.5) 3)
(segment 2 (point 6.3 0 0 0.5) (point 206.3 0 0 0.2) 3)
```
2. CV area = `1062.49`
Segment 1 is a zero length cable and shouldn't contribute to the CV area (as far as I understand), which would mean that the answer is incorrect. 

***************************************
This can be replicated using the `single-cell` [example](https://github.com/arbor-sim/arbor/blob/master/example/single/single.cpp).

Morphology 1 is the default morphology.
Morphology 2 is the generated from the following SWC file: 

```
1 1  -6.3 0.0 0.0 6.3 -1
2 1   6.3 0.0 0.0 6.3  1
3 3   6.3 0.0 0.0 0.5  2
4 3 206.3 0.0 0.0 0.2  3
```

**Comment by halfflat** [comment]
It turns out there is an explanation, and it might not be a bug.

The difference between the two is that the zero-length segment contributes a surface area that represents the anulus with outer radius 6.3 and inner radius 0.5. Conceptually, it's what you would be left with if you had a non-zero length segment with these radii, and took the limit as the length went to zero. With the zero-length segment in-place, the gap between the two segments on other side is 'filled-in'.

Because of the hand-wavey limit picture above, I am inclined to think it is not a bug: the two segment trees describe distinct morphologies, one where the first and last segments are disconnected, and one where they are not.

**Comment by bcumming** [comment]
The zero-length segment with varying radius has non-zero surface area and zero volume?

**Comment by halfflat** [comment]
Yup! In dodgy ASCII art, the difference is between:
```
   |   |
   |   |
|         |
|         |
```
and
```
   |   |
___|   |___
|         |
|         |
```

A related argument: suppose it wasn't length zero, but _close_ to zero. As the length goes towards zero, the volume of the segment goes to zero but the area does not.

**Comment by noraabiakar** [comment]
Okay. I also think it's not a bug.
The two representations of the morphology in [this example](https://arbor.readthedocs.io/en/latest/tutorial/single_cell_detailed.html) are then not equivalent, and people who scrutinize the results will notice a discrepancy. We can add an explanation of the phenomenon in the [SWC docs](https://arbor.readthedocs.io/en/latest/concepts/morphology.html#swc) and add a note to the example saying that the morphologies are slightly different with a link to the explanation. Does that sound good?
