### ISSUE TITLE
[PIP][bug] Install Arbor on older pip and certain systems fails.

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1320]
Two pip problems. Easy one first:

1. Installing with a pre v20 pip, which autoselects user dir or system dir as package installation path, `pip install arbor` fails with a write permission denied. I tried wrapping this in an if-statement, but its not triggered:

https://github.com/arbor-sim/arbor/blob/master/python/CMakeLists.txt#L89

How can we present a nicer and helpful error message? (Like, use sudo or --user.) Remember, this is for first time users.

2. On the ebrains jupyterlab, I tried `pip install arbor` as well. The error is a bit different: I see a similar complaint to a local install, something about missing git submodules, but locally the build then goes ahead, but on ebrains I get a 'Failed to build arbor' and I get that error *again* and then it blows up. Attached a log of `pip install arbor --verbose > log 2>&1`. Anyone an idea what goes on?

[piparborebrains.txt](https://github.com/arbor-sim/arbor/files/5855621/piparborebrains.txt)

**Comment by bcumming** [comment]
Points 1. and 2. are completely separate issues.

I am in a bit of a bind over what sort of error to present to users about using pre v20 pip. That standard, well defined and understood result of trying to install to a path where you don't have write permissions is that you will get an error message. And with older versions of pip, it tries to install to the system paths by default, and we expect to get an error.

The spot to detect that the user intends to install to a path to which they don't have write permissions would be in `setup.py`. If we catch that in the `CMakeLists.txt`, then the error message will be buried inside the CMake output, and it won't matter how clear the message is, it will be hard to find (see the description of point 2. below). If you detect the error early, in `setup.py`, you might be able to print a nice message before too much text has been generated in the output log.

Additionally, build tools (like CMake or autotools) will not warn or give an error message if the user does not have write permissions to the installation path during configure, because the build process should only use `sudo` for the install part:
```
cmake /path/to/my/source
make
sudo make install
```
So we don't want to add non-standard checks during the configure stage, i.e. when make that first call to cmake.

The problem with ebrains is unrelated to pip: it is an issue with the environment with Jupyter Hub on EBRAINS. Specifically, it has an ancient version of gcc. From the log file that was attached:
```
    -------------------- Configure CMake
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
...
    CMake Error in /tmp/pip-install-_4shrpvg/arbor/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeTmp/CMakeLists.txt:
      Target "cmTC_656a3" requires the language dialect "CXX17" , but CMake does
      not know the compile flags to use to enable it.
```
We require a version of gcc that supports C++17, which gcc 4.8 doesn't.

@thorstenhater submitted a ticket to EBRAINS around 4 months ago, asking that they upgrade the version of gcc available, but I don't know if we ever made any progress there.

I agree that it would be good if we could present error messages in an easy to process manner: however pip prints out a whole heap of boilerplate cruft around the error message. The error message here is actually quite clear, however this boilerplate makes it hard to isolate the error.

**Comment by brenthuisman** [comment]
1.  `pip install arbor` does not require a specific path from the user, so a path error is not something I expect. The output is indeed very verbose (even without `--verbose`), so a better message is required.
2. Setting the CC and CXX env vars does result in CMake finding the right versions. Question: why doesn't CMake pickup gcc/g++ in the path? Those are the right version.

The troubles aren't over unfortunately:
```
    CMake Error at /opt/app-root/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
      Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Python3_LIBRARIES
      Development Development.Module Development.Embed) (found suitable version
      "3.6.9", minimum required is "3.6.0")
    Call Stack (most recent call first):
      /opt/app-root/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
      /opt/app-root/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython/Support.cmake:2984 (find_package_handle_standard_args)
      /opt/app-root/lib/python3.6/site-packages/cmake/data/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
      CMakeLists.txt:257 (find_package)
```
Having Python dev packages on ebrains is being worked on.
