### ISSUE TITLE
Retire Travis

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1338]
See other discussions before.

Before PR:
- finish GitHub Actions support in #1337 

For the PR:
- remove all travis scripts and configes (`.travis.yml` and `scripts/travis` path)
- remove all mention of travis from the docs
- remove travis badge from `readme.md`

After the PR:
- @bcumming removes integration of Travis app on GitHub.

**Comment by bcumming** [comment]
Regardless of my opinion, this has to happen because Travis will no longer support free accounts like ours by the end of the month.

That said, the sooner the better, due to the increased overheads of using Travis as they wind down free tier support.

I would be in favor of removing this as soon as GitHub actions cover clang and gcc under ubuntu, and MacOS 10 and 11.

**Comment by thorstenhater** [comment]
Quick update: MacOS 11.0 is not yet supported, only as a 'private preview' whatever this is supposed to mean and how long this will persist.

**Comment by bcumming** [comment]
We are using MacOS 10. From the Travis logs
`146c3525-89f7-462c-9f77-38a4becedfc4 travis-ci-macos10.15.7-xcode12.0.1-1601960625`

**Comment by bcumming** [comment]
I am gong to turn off Travis now that @thorstenhater 's GitHub Actions are happily testing MacOs.
