### ISSUE TITLE
Discussion: synapse identification.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#1394]
As raised in the comments on PR #1235, it is hard to identify synapses associated with a decor placement given by a locset expression:
* The number of created synapses depends upon the thingification of the locset expression. If this number is not exactly one for all placed synapses, the value returned by `decor::place()` will be incorrect.
* When the locset involves simulation-construction time parameters (e.g. per-sim random seeds, which we plan on supporting), it is not even possible in principle to determine the indices of the corresponding synapses, without independently evaluating all the placement expressions against the corresponding mprovider object, which would have to be obtained via a new interface.

The flat nature of decor is at odds with the requirement that there be an `mprovider` object in hand with which to evaluate the given locset expressions.

A related issue at a higher level arises when describing population/projection style network descriptions: when connection endpoints require both a cell from a population and a synapse on that cell, there must be a language by which the relevant synapse or subset of synapses can be identified independently of a particular cell.

A first rough proposal:
* Targets (in particular, synapses on cable cells) are associated with one (or possible more) labels. These might be text labels, or numeric. For cable cell decor, these would constitute part of the synapse description.
* Connection targets as returned by `recipe::connections_on` are given in terms of target gid, target synapse label, and possibly a third parameter which is interpreted specifically by a cable-kind specific handler and which describes how to resolve ambiguity when the label does not correspond to exactly one end-point.
* A translation phase resolves these label descriptions of targets into concrete target ids after cell groups have instantiated the cells.

A similar problem arose with probe ids: probe ids are assigned sequentially on a given cell, but each id may correspond to zero or more actual probes, depending upon the corresponding locset evaluation. This was less of an issue, because the metadata for the probes associated with a probe id is intended to be queried by the application after a simulation object is created and the corresponding cells are fully realized.

**Comment by brenthuisman** [comment]
Documentation on indices is lacking, apart from cell ``gid``s. It would help to stop calling them 'indices', but start calling them 'synapse id', 'probe id', etc. The use of `arbor.cell_member` in setting up `arbor.connection` is not helping this confusion: you pass in a cell local index, but it depends on the position of the argument to `arbor.connection` to which bag of things the index will point to. (I see that it makes sense for the implementation.)

Some user perspectives:
* I'd like to have a way to query a cell description/decor for all its indices for each category. Give me a list of all synapse sites, generators, probes, (am I missing an index?).
* Can I can get a locset expression for `synapse12`?
* If `decor.place()` returns an invalid index, then I think currently there is no way to know to which locset an index corresponds?
* Can we get rid of `cell_member`? A (``gid``,index) tuple makes more sense than a special type, given the way you use them when creating connections. Alternatively, `arbor.endpoint.source` and `arbor.endpoint.dest` types would be more descriptive, even if they're functionally equivalent to `arbor.cell_member`.

At a later stage, we can think about 'higher level' connections/connection site descriptions. When at some point we have a 'population DSL', which allows us to create populations of various cell descriptions, and describe their connections statistically rather than individually, it will be important to be able to output a particular instantiation of such a network/recipe in order to debug possible mistakes in the DSL input, and be able to reproduce simulations. We'd need well defined and reproducible indexing, wouldn't we?

**Comment by halfflat** [comment]
Summary of decisions from Zoom discussion 20210202:
* Go with either string labels, or type-erased things that can be hashed and equality compared.
* We will need the same or similar system for spike sources and gap junction sites; consider also using these labels to replace probe ids.
* Initially, we provide round-robin assignment of synapses to connections against their labels on any given cell, leaving open the possibility of connections specifying an additional parameter specifying how to make this resolution.
* By default, a connection against a label with zero targets is a sim initialization-time error. If we include the resolution parameter mentioned above, this can allow the possibility of such connections as being treated as simply non-existent.
