### ISSUE TITLE
Discussion: Automate Release / Deployment

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1414]
# Goals

- Reduce workload
- Enable more frequent releases to make it easier to focus on tasks and prioritize
- Simpler review for partners and 'stakeholders'
- *Non-goal*: completely automated releases

# Release Notes

- Where do we store them?
   - Proposal: CHANGELOG file in tree.
    - What do we record? Options
        1.  Closed Issues since last release/tag. Filtered by release manager.
        2. List of commits since last release/tag. Filtered by release manager.
            ```bash
            git log $(git describe --tags --abbrev=0)..HEAD --oneline
            ```

# Release planning

- within month of release, release planning session for the *next* release
- create an aspirational Release Note wiki page like this.

# Things to Automate
- [ ] CI
  - [x] Run the C++ examples
  - [ ] on `-rc` tag: auto-upload Python wheels to TestPyPI
  - [ ] on `-rc` tag: install from wheels and run tests and examples
  - [ ] on `-rc` tag : install from pip via source with all (possible!) flags and run tests and examples
- [ ] Add a script to
   1. Bump VERSION (should be patch-level + `-rc` by default)
   2. git tag from VERSION file
   3. push tagged branch to read-the-docs.io
   4. push to PyPI
   5. update spack package
- Github release
  - e.g. https://github.com/ncipollo/release-action

# Other

- [ ] Update [Release Process](https://github.com/arbor-sim/arbor/wiki/Release-Process) page.
   - [ ] which steps are automated and link to the script/thing that automates them.
   - [X] add spack package to process.
- [ ] Investigate and document what pip does when asked for a flag that's not present in the wheel.
- [ ] Investigate how `MANIFEST` and `setup.cfg` are updated.

**Comment by schmitts** [comment]
* release tarball incl. checkout out submodules (cf. https://github.com/arbor-sim/arbor/blob/master/scripts/create_tarball.sh)
* update spack package (cf. https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/arbor/package.py)

**Comment by bcumming** [comment]
Can we please have a description of what is meant by "automate release" ;)

**Comment by thorstenhater** [comment]
This is a placeholder at the moment from our ongoing discussion.

**Comment by brenthuisman** [comment]
Be patient, my young padawans :) @thorstenhater and I will round the message out ASAP.

**Comment by halfflat** [comment]
Should a change log be regarded as release notes, or do we keep these separate?
For release notes, I propose:
* Release notes are collated in a single file in the repo, most recent release at the top.
* When we add a feature in a PR that should appear in the release notes, we update the release notes as part of the PR.
* The heading of the release notes and/or change log is checked or amended as an automatic part of the release process.
* The automated process is also responsible for including a list of issues closed between this release and the previous.

**Comment by brenthuisman** [comment]
The updated Issue message has two proposals, one of them a `CHANGELOG` file which is I think what you propose in 1. We haven't proposed how to create/maintain it any more specific then: up to the release manager.

Having a line added to this document as part of the PR procedure is the obvious approach. We could still argue that some smaller PRs don't 'deserve' a mention. Does anyone argue that?

I think what you propose in 3. is the other proposal in the Issue message. I'm not sure if you mean to integrate the two methods? Every closed Issue will map to at least one merged PR/line in `CHANGELOG`, so that would be unnecessary, but maybe I misunderstand. A reason to base the changelog off of closed Issues could be that this is a more concise and clear summary.

**Comment by bcumming** [comment]
Regarding release notes, we need some method of keeping track of them as changes are made. That could be fully automatic, but that might lead to very boring release notes that don't clearly emphasize the big / important changes.
The current approach of manually going over the commit/PR history since the last release is the other extreme, and is not much fun to do all in one go.

**Comment by halfflat** [comment]
For release notes, they are going to be read by humans (ideally) with a view to determining what has significantly changed, or what new features might have become available. Consequently, I think it will need to be updated manually, so that we can do a good job of that.

Any given PR might not want to touch the release notes, but for anything that passes this sort of bar, we could insist that the PR update this document accordingly.

For example, master might have a release notes file:
```
Next release
========

* Support added for blue neurons.

Version 2.3.4 20240108
===============

* All frobnicators also farnarkle unless the arkle is out of bounds.
* Support added for green neurons.
…
```

A PR adds the long requested background MUSIC feature, and includes an update to the release notes file, so it that it now reads
```
Next release
========

* Background MUSIC support added, allowing both classical co-simulation configurations and jazz configurations.
* Support added for blue neurons.

Version 2.3.4 20240108
===============
…
```

If the PR is merged, this document is updated. And at release time, a script would replace the heading `Next release` with e.g. `Version 2.4.0 20240223`.

**Comment by bcumming** [comment]
Looks like a nice approach.

**Comment by thorstenhater** [comment]
Escaped auto-close.
