### ISSUE TITLE
Add IWYU

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1460]
Include What You Use automatically checks (and if asked fixes) includes such that includes are
- sorted by type (system, public, local)
- minimal: nothing unused is included
- exhaustive: everything needed is directly (not transitively) included

https://include-what-you-use.org/

These rules are applied to headers and implementation files, if needed/possible things are shuffled
from header to implementation.

Why? This automates part of our guidelines :tada:, improves compile times, makes the code more robust
and helps poor OSX folks with overly lenient compilers.

I have tried it, but on OSX it mistreats system libraries, in particular LLVM internal headers are included instead
of the public ones, eg hash over unordered map.

Here is the invocation I have used as a starting point
```
 iwyu_tool.py -j4 -p . -- -Xiwyu --no_comments -Xiwyu --cxx17ns
 ```
To try you will need to have a compilation database. 

Part of #1317

**Comment by bcumming** [comment]
@noraabiakar investigated this, and found that it wasn't suitable.
She could leave a comment, and close the issue?

**Comment by noraabiakar** [comment]
Compiling arbor with IWYU generates a log of suggested changes, which can then be applied using a python script.

Some observed issues:

* Getting to a point where no changes are suggested requires several iterations where some of the changes suggested in a previous iteration are then undone.
* My personal IDE (clangd-based inspection) marks a lot of the newly added headers as unusued.
* It suggests incorrect transformations that break the build.
* The python script seems to be buggy. It'll sometimes just shuffle includes in a file without removing or adding anything. The reason seems to be that there other suggestions in the generated log file that aren't being picked up.
* The python script applies sub-optimal sorting. It'll only sort the newly added headers relative to one another. It wont insert them in the correct spot relative to other headers of the same type. A not insignificant amount of manual work is needed to make things look right.
* The python scripts adds arbor's public headers between quotes as opposed to angle brackets.

I don't think the tool is mature enough to incorporate into our workflow. 

Closing this issue: any future changes to the arbor headers can be handled in a separate issue.
