### ISSUE TITLE
[CI/bors] ARM testing

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1498]
1. Can we have bors run our testsuite on the A64FX machines at ault? @haampie perhaps you know if this is possible and how we should go about this?
2. Alternatively, we should forego of SVE testing and settle for a Qemu GA.

**Comment by haampie** [comment]
There's a couple issues: no gitlab runner on ault, no container runtime compiled for arm, and the (awkward) way we do things now (build a docker image on a different cluster, push it to a registry, run tests on target machine) complicates things, since we don't have an arm-machine where we can build images easily. Maybe https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/ is useful, but I have no experience with that. There's also a qemu + buildx github action.

There's some discussion about building images inside sarus so we wouldn't have to do this dance of building on kubernetes and running on piz daint / ault, which would simplify compilation too as you could just run -march=native if you don't care about portability that much.

**Comment by brenthuisman** [comment]
Thanks for the info.

I had a look at the Qemu GA, but I'm not sure if we can test SVE vectorization that way (only NEON comes with aarch64). But if there is no timeline for CI on ault, then it'll have to do.
