### ISSUE TITLE
Morphology causes NaN membrane values

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1526]
Running the attached script with Arbor 02dd4326f0fdbb2e5c64f76a32c4f44320e9ee9d leads to NaN values for the membrane voltage.

Maybe related to `0` radius, cf. https://mcnest.slack.com/archives/C04NU4NMK/p1620833904155700.

[membrane_nan.py.gz](https://github.com/arbor-sim/arbor/files/6468161/membrane_nan.py.gz)

**Comment by noraabiakar** [comment]
This is @halfflat's area of expertise. I think the issue may be this line: https://github.com/arbor-sim/arbor/blob/master/arbor/morph/embed_pwlin.cpp#L309

**Comment by schmitts** [comment]
```
            double ixa_1 = ixa_0 + (dx>0? dx/(pi*r0*r1): 0);
            std:cout << ixa_1 << " " << dx << " " << r0 << " " << r1 << '\n';
```

yields

```
0.212207 6 3 3
7.69249 23.5 1 1
inf 80.7775 1 0
inf 80.7775 1 0
```

So `r1` is zero and `ixa1` is `inf`.

**Comment by halfflat** [comment]
The easy solution would be to ban zero-radius points :)

Fixing this properly might be a little involved; internally we use things like `ixa` to interpolate the resistivity, but the resistivity is infinite at the exact point at where the radius is zero. It doesn't mean that the modelled system is physically unreasonable — especially when these zero radius points are strictly terminal — but it will require either some special case checking, or a more robust rational function interpolator.

**Comment by halfflat** [comment]
Update: it is definitely a problem with our rational function evaluator, which is insufficiently robust. In principle, these interpolating functions are well defined even with some node values that might be ±∞ when the order of the denominator is greater than zero, but the recursive evaluator we use can fail at nodes in this circumstance.

We're using a procedure described by [F. M. Larkin (1967)](https://academic.oup.com/comjnl/article-pdf/10/2/178/963618/10-2-178.pdf), but there are more recent alternatives that are more reliable, such as [S. L. Loi and A. W. McInnes (1983)](http://dx.doi.org/10.1007/BF01937330) which we could try in principle.

At some cost in performance, we could add a check for when these rational functions are evaluated at node points and return then the node value directly, which would fix the immediate issue.

There is another issue though, which is what to do when we have a _non-terminal_ zero radius point? Our current approach, where we store the values of the integrated cross-sectional area starting from the root point will fail, because it will simply be +∞ for every point after the first zero-radius point. A way to resolve this problem 'correctly' is to divide the representation of this function into discrete domains, and when we try to integrate it over a cable segment, we say it is infinite if it crossed domains, or else we interpolate within the domain as normal. On the other hand, such a model has that the neuron is comprised of electrically isolated components, which frankly doesn't sound especially plausible, biologically speaking, and I think it might be reasonable to prohibit such models.
