### ISSUE TITLE
Have `load_*` morphology loaders accept file-like objects

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1537]
It's typical in Python that where you can provide a filename as a str, you can also provide any file-like object (anything with a `.read` method basically), but the arbor morphology parsers don't do this:

```python
Traceback (most recent call last):
  File "/home/robin/test-cat/arb_test.py", line 3, in <module>
    morph = arbor.load_asc(open("stellate.asc", "r"))
TypeError: load_asc(): incompatible function arguments. The following argument types are supported:
    1. (filename: str) -> arbor._arbor.asc_morphology

Invoked with: <_io.TextIOWrapper name='stellate.asc' mode='r' encoding='UTF-8'>
```

Use-cases include various bytestreams, or files that were already read into memory for some other purpose.

**Comment by halfflat** [comment]
This is related to a point raised in #1507 — outside `dlopen` etc., we can avoid a bunch of platform-specific problems by having the C++ arborio functions take strings/string_views of the things we want to parse, rather than paths. At least outside of representations in HDF5, SONATA etc.

If we do this, then the Python interfaces can take paths and file-objects, or instead could take the content directly as strings. What are your thoughts, @Helveg?

**Comment by thorstenhater** [comment]
#1459 is the pythonic way ;) That said, it's probably as easy as calling `str()` on the path-like, if we want that.

**Comment by Helveg** [comment]
Right sorry, this is a dupe of #1459. I'd take the file-like objects though, not their strings. 1 less thing for us to do ;p

**Comment by thorstenhater** [comment]
https://en.wikipedia.org/wiki/Meal,_Ready-to-Eat?

**Comment by Helveg** [comment]
Close, https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by thorstenhater** [comment]
yeah, but that's spelled mWe, not mRe?

**Comment by thorstenhater** [comment]
I am closing this on grounds of being a duplicate.
