### ISSUE TITLE
Allow to identify probes and handles by string

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1539]
Currently handles on probes can be retrieved via their probe id. This puts the burden on the user to do the bookkeeping. A user defined tag/label/id would be better. @halfflat proposed something along the following lines:

```python
class some_recipe(arbor.recipe):
  # ...
  def probes(self, gid):
    return [(arbor.cell_probe_membrane_voltage("(on-branches 0.5)"), "farnarkle"), ...]
```

```python
h = sim.sample("farnarkle", ...)
```

**Comment by halfflat** [comment]
Some notes:
* Probe id tags could be strings only in the Python interface, or we could make them strings in the C++ API too. For Python only, we'd associate the strings with unique integer tags behind the scenes.
* While on the C++ side it is reasonable and expected that a sampler callback might handle multiple probe ids, with differing value and metadata types, the Python sampling API presents a more straightforward interface, where a request to sample a probe gives a handle associated with one probe id and correspondingly, a single sample value type etc. Consequently, `sim.sample("farnarkle", ...)` should return a collection of handles, one per matching probe id.
* The C++ API would have to be extended to allow matching probes by tags.
* We'd also have to add a method for retrieving the set of (local) probe ids associated with a probe-matching predicate, so that  the Python lib can set up the individual handles and sinks for each one.
* There remains the problem of working out which handle means which probe id. We could make the handle(s) returned by the Python  `sample`  method hold on to more info, so e.g. a handle `h` could report its corresponding probe id with `h.id`, the tag of that probe id with `h.tag`, and the sampling policy with `h.policy`.

**Comment by thorstenhater** [comment]
Done in #2213
