### ISSUE TITLE
Support for axial diffusion

### ISSUE THREAD

**Issue by schmitts** [arbor-sim/arbor#1651]
Cf. "Mechanism of signal spreading" in "Biophysics of Biochemical Signaling in Dendritic Spines: Implications in Synaptic Plasticity" by Yasuda (2017) https://doi.org/10.1016/j.bpj.2017.07.029.

"Axial" is along the cable.

**Comment by thorstenhater** [comment]
Based on discussions with @schmitts and internally, the plan is to implement the following:

Diffusion of the internal concentration of arbitrary, user-specified ion species according to 

> Xi' = ß∆ Xi

Note that we -- for the time being -- ignore the possibility of `ß` varying  spatially or temporaly, nor do we
allow for active transport. The diffusion parameter `ß` is defined by a user-specified constant and the 
cross-section of the cable.

We implicitly assume here that ionic diffusion is on much larger time-scales than voltage propagation.
Otherwise, the discretisation would have to take into account the faster process. I think that is a sensible
assumption based on physics, but biologists are encouraged to correct me here. Based on essentially the
same argument, we do not plan to feed back currents caused by ionic transport into the cable equation
(just the effect of `Xi`/`Xo` on the overall state, if any).

@schmitts Is that sufficient for your plans and are our assumpions biologically sane?

This enables us to (more or less) directly re-use the voltage-solver and thus provide a quick implementation
based on well-tested components.

**Comment by schmitts** [comment]
Thanks, @thorstenhater, for the write-up! No further requirements from our side.

**Comment by schmitts** [comment]
Cf. PR #1729

**Comment by thorstenhater** [comment]
From private communication w/ @schmitts: FIPPA works on an 1d simulation, which could and should be used for validation.

**Comment by schmitts** [comment]
Please find attached the bare-bones diffusion process we would need. In addition to some initial concentration of calcium (or any kind of diffusing element), point mechanisms have to have the possibility to increase the concentration at their respective positions in space.

[diffusion_mock.py.gz](https://github.com/arbor-sim/arbor/files/8232988/diffusion_mock.py.gz)
