### ISSUE TITLE
Defaults: creating a context saturating local cpu

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1692]
For new users, and users of the scientific Python ecosystem, having to set the number of threads manually for local use of Arbor is a bit surprising. In this issue I'd like to discuss how we can give users a better default while keeping the amount of magic down for more advanced use of Arbor.

Something like `arbor.context(use_all_threads=True)`, or `arbor.all_local_threads_context()` instead of `arbor.context()`. `arbor.single_cell_model` would also use that context or setting.

For reference, [there was an attempt](https://github.com/arbor-sim/arbor/pull/1415). I think the code there is perfectly valid.

**Comment by thorstenhater** [comment]
Hi,

I see where you are coming from, why this is interesting to users and especially beginners. However, the discussion in https://github.com/arbor-sim/arbor/pull/1415 is still relevant in as much as that the general case is not solvable. Therefore, yes, let us find a solution that addresses the immediate need.

Regarding the options listed above

- Passing a flag leads to this unfortunate accident `context(threads=1, use_all_threads=True)`. This might happen in various situations eg code generation, bad copy-paste, ... . What to do in this case? Throw an error? Do we also throw if thread count and all threads are accidentally the same number? 
Apart from this, I find it sub-optimal to have two args for saying the same thing.
- Having constructors for common use-cases is more tenable, but suffers from combinatoric explosion. Nevertheless, I think it's the better of the two options. However, which are these 'common cases', where do we draw the line?
- What I would be actually opposed to is to have different behaviours in C++ and Python, since it complicates transitioning between them.

My preferred solution would be this (or similar)
```py
comm = ...
context(threads=4, mpi=comm) # As currently, give 4 threads (per local MPI proc?)
context('cores', mpi=comm) # Use one thread per physical core, divided between the MPI procs on this node.
context(threads='threads', mpi=comm) #  Use one thread per hardware thread divided between the MPI procs on this node.
```
We could also add this in C++ by use of a newtype or enum. I am tempted however to say _if you use MPI we will only take numbers_ (same for the default contexts above, only threads, no MPI) on grounds that this is the realm of advanced users.

The question on how to actually _determine_ the number of threads remains open though. Whatever method is used should be bulletproof. Here's the wrinkles to think about
- containers / cgroups and ilk: Cannot use `/proc/` (nor possibly Python modules; subject to experimentation).
- thread_masks established by taskset and Co
- should we honour OMP_NUM_THREADS / SLURM variables?

For all proposals here (including mine!) we should be really careful with naming. I personnally find the `cores` and `threads` terminology intuitive (and it's aligned with SLURM), but YMMV.

**Comment by bcumming** [comment]
The problem can't be solved generally (e.g. on MacOS, who knows!)
The current solution is to provide some helpers that make a best attempt at determining core counts and reading environment variables, and putting them in a separate library.

Making defaults that detect core counts will require that it works very robustly... and given the non-exhaustive list of potential issues that @thorstenhater mentions, I think you really are better off letting the user figure out how many cores are available, with some helper functions.

**Comment by thorstenhater** [comment]
So, we are a bit torn between users' needs and the practicalities of robust thread detection. This is why I would argue the default `threads=1, mpi=None, gpu=None` is still ok, but we should have an easy way to opt in to using more. Rationale
is that the easy way should cover 90% of the cases; not many people are running in containers and tweak masks.

Here's my suggestion
```py
# Set up one thread per detected physical core.
context(threads='cores')
# Set up one thread per detected logical core.
context(threads='threads')
```
- This is strictly a convenience feature and can live in Python land
- If MPI is used, these numbers are distribute evenly among local MPI tasks.
- Thread detection should be done as best-effort, with the following guidelines
  - We are targetting mainly Linux-based systems, so Arbor on Linux should go the extra mile
    - honour task affinity
    - detect cgroups usable cores
  - On MacOS, Docker et al are run in VMs, so we are dealing with a much simpler situation

I did some preliminary scanning of Python options, and `os.cpu_count` seems to be a good start for detecting the raw count of logical cores. On Linux, using `os.sched_getaffinity(0)` yields more detailled information and respects affinity masks.
That would quite easily allow us to build `threads=threads` on MacOS and Linux. Weeding out SMT from this is another question. Both calls may bail or return `None` which we should propagate to the user.

**Comment by brenthuisman** [comment]
I like the proposal of @thorstenhater; `context(threads='cores')` and `context(threads='threads')`. If we're going to go into the task affinity/cgroup detection route, more correct would be to say `context(threads='avail_cores')` and `context(threads='avail_threads')`. But maybe that route is making a simple thing too complicated: this Feature Request not meant to help the user squeeze every cycle out of the CPU or HPC, but to get, seeing as we all have 4-8 logical cores at minimum nowadays, get a good approximation of the maximum performance out of their hardware when using Arbor on their local machine.

I haven't found a way to get the number of _cores_ out using stdlib only. The [psutil](https://pypi.org/project/psutil/) library lets you do `psutil.cpu_count(logical=False)` which gets at the right number, but is not stdlib.

Does combining `threads='threads'` with MPI make sense? If a user uses MPI, I'd say we've left the scenario where they're testing on their local machine, they can be expected to set the number of threads accordingly. One might assume that in combination with MPI this argument implies to set the thread number on each node to whatever the max is on that node.

**Comment by brenthuisman** [comment]
`std::thread::hardware_concurrency()` respects `taskset`, which meets the requirements that affinity is respected/used. Since `hardware_concurrency()` is available on multiple platforms (not only Linux), it is better than `os.sched_getaffinity()`.

If we solve this in C++, then we might as well expose this option, for instance through a magic number, say `-1`. `threads` could then be a class with an implicit constructor from `int` which uses `hardware_concurrency()` to set the thread number when the magic number is encountered. One thing to check for is then the possibility of `hardware_concurrency()` returning 0 or less, upon which and error should be thrown, or, `threads` set to 1.
