### ISSUE TITLE
Formal dependency version management

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1731]
## Goal

1. Avoid updating dependencies without having checked that they match (e.g. git submodule hash and Spack file version tag), that they are in fact available (git submodules are updated more frequently than Spack files) and taking into account an important runtime environment of Arbor: [the EBrains Jupyterlab](https://lab.ebrains.eu) (e.g. it currently has Python 3.6, so Arbor can't drop compatibility for it until that changes).

2. Ensure that Spack builds of releases versions of Arbor are reproducible, by which I mean that building any Arbor version other than `master`, we fix the (range of) versions of dependencies.

## Rationale

1. We've [just established](https://github.com/arbor-sim/arbor/issues/1717#issuecomment-947552886) that a dependency had a git submodule commit hash that did not match the version in the Spack file. A solution without reverting is not trivial: dependencies in Spack files can only rely on stated versions in their respective Spack file, which may be trailing release tags in the git repo, and then lead Spack to resolve to the master branch which is present in many Spack files, which led to confusion. It's important to avoid these events and that building Arbor does what it says on the tin ;)

2. a. As the Spack ecosystem ages, dep requirements of older versions is going to significantly diverge from current dep version requirements. We don't test older versions with current dependencies as a matter of course, and I'm not sure we are going to. Freezing older versions at specific dependency versions may be the only practical way we can insure those older versions remain usable/behave predictably/have been actually tested. In addition: we're not going to be in control of all build envs (EBrains). I'm not fond of relying on users/builders speccing the env out in excruciating detail, because I'm not sure it'll be done correctly (it's hard for me!); freezing the deps of older versions seems like a better idea to ensure spack install my_package@some_old_version results in something stable over time. Concrete use-case: processing pipelines that researchers store and re-use perhaps for decades. I'm not sure what's optimal here yet either, so any opinions on how to keep such pipelines working over longer timespans is appreciated!
  b. Many packages define a master version, which will get you their current master branch. Together with the fact that Spack file updates trail project releases by some time, this may mean in practice that specific versions may be pulling in unspecific dependency versions. That I am not fond of. When building our package's master branch I'm OK with pulling in deps master branches, but not for any version release.

## Discussion

Even for Spack CI of the master branch, the problem under 2.b can be a bit of a headache, because due to the update lag, Spack CI may be testing other versions of dependencies than regular CI. I propose to not address this right now, but merely bring it to your attention. In case someone feels strongly that we must address this, please do.

## Implementation

* Any bump in dependency version should require a bit more review than we currently do. A bump in Python minver almost passed me by, and PR1711 was merged. I would propose that any change needs vetting by at least two reviewers, or a dev team quorum. Alternatively, we could formalize the role of release manager (I guess practically I've taken it over from @bcumming) and require a green light from that role. Part of the work of the release manager is then to actively verify no objections exist to the version bump.

* We should expand our Spack CI to all listed (i.e. older) versions. This only needs to be done upon prerelease of a new Arbor version. It's good to ensure older releases pass the tests when built with more recent dependencies. If those tests fail, the maximum version of a dependency shall be capped in the Spack file at the last known good version (i.e. the version as present at the time of the previous release). Performing these checks is a new item on the checklist for the release manager.

**Comment by muffgaga** [comment]
Some comments :)

> or: the EBrains Jupyterlab (e.g. it currently has Python 3.6, so Arbor can't drop compatibility for it until that changes).

I just had a look and that's the `spack.yaml` for the EBRAINS software release from last week:
```
spack:
  specs:
    # Base
    - python@3.8.11 %gcc@10.3.0
    # Notebook
    - py-jupyter %gcc@10.3.0
    - py-ipython %gcc@10.3.0
    - py-ipykernel %gcc@10.3.0
    - py-notebook %gcc@10.3.0
    # General
    - py-pip %gcc@10.3.0
    - py-numpy %gcc@10.3.0
    - py-scipy %gcc@10.3.0
    - py-pandas %gcc@10.3.0
    - py-seaborn %gcc@10.3.0
    - py-matplotlib %gcc@10.3.0
    # EBRAINS simulators
    - arbor +mpi ^python@3:3.9 %gcc@10.3.0
# nest, neuron, BrainScaleS, whatever
```


> dependencies in Spack files can only rely on stated versions in their respective Spack file, which may be trailing release tags in the git repo

A package (e.g. arbor) may depend on other packages at specified commit hashes… it's somewhat unusual but still better than performing vendored builds.

**Comment by muffgaga** [comment]
> What I propose is that we add CI for older versions, and cap deps in case they start breaking. The alternative, patch releases for older versions, is not tenable. Having versions in the Spack file imply they are buildable, and I propose to ensure that they in fact do.

Sure, but that's "normal" for spack packages? You specify multiple versions and you constrain your dependencies for these versions (e.g. older arbor could require a differernt cuda version range than the newest) → `depends_on('cuda@12.3:12.4' , when='@0.1.2.3:0.1.2.5')`.
My suggestion regarding "patching" was rather towards avoiding a situation where you have to depend on an unreleased version in a dependency. There the better approach would be to stick to the latest released one and patch the problem away (I assume that this is the reason for non-released version dependencies… at least that's what we usually do… some dependency breaks on gcc@11.2.0 → look for new version, none found, patch it via spack (and create upstream PR), update dependency when they released a new version).


> An alternative could be to simply remove older versions from the Spack file. But I don't prefer that.

I agree: Keeping old versions buildable has advantages, e.g. users who want to reproduce behavior from older versions. And removing build descriptions for older versions is extra work… and if somebody reports a build problem for an older arbor version caused by some depdency it's also reasonable to add constraints to the package file.
However, in my experience keeping up with the development is already hard (ok, we have approx. 400 dependencies for our BrainScaleS software stack, arbor has 79 when enabling all variants) and adding tasks by also looking at old versions is even harder.

**Comment by brenthuisman** [comment]
Vendored `random123` has modification, can't be replaced with a submodule as-is.

**Comment by bcumming** [comment]
I left this comment on a PR, and I post it here because it is relevant.

I find the rationale in the document a little bit difficult to follow, because the minimum supported version of a dependency and the version in a submodule are not the same thing, and they shouldn't be conflated.

On one hand it is not too important which version we use as submodules because:
- the use of sub modules is a convenience for developers, and should be avoided when installing the software in production (it doesn't play nice when installed alongside other software and will drive maintainers of software environments to despair.)
- installation via pip relies on it as the least awful solution, unfortunately.

On the other hand, because the sub modules are used in all of our CI/CD pipelines, except the spack pipeline
- we should use use the minimum supported version, because the minimum supported versions should always be tested in CI/CD.

If we stop using the sub modules in CI, then we would more flexibility in choosing whichever versions for the submodules.

**Comment by brenthuisman** [comment]
Summary of team meeting on this subject today:

* submodularize
    * ext/json
    * ext/random123
    * test/gtest.h
        * also move to ext/
* move pybind to ext/
* in `dependencies.csv` in #1865
    * distinguish tool from dependency
    * add above submodules
* bump versions:
    * leave submodules to lowest possible
    * modify update Action to actually pull and test.

Criteria: if provided by a package manager, then can be git submodule.

**Comment by brenthuisman** [comment]
## Update:

Most of the above has been implemented. One thing is missing:

- [ ] Make it possible to build with an external Google Test.

## Proposal

- Update `doc/contrib/dependency-management.rst` with the following:
  1. We bump the submodule and Spack dep in tandem, and never past Spack latest release, and only if there's demonstrated breaking or changes that we require.
  2. Some Spack deps are unversioned, and but the Git submodules are. We leave it as-is, until there is reason to bump, and then they'll be brought in line.
  This results in us testing the lowest known working versions of the submodules in most of our CI, and the Spack CI tests with a reasonably current version (as per Spack releases), so we have some advance notification of breakage with more recent versions.

OR

- Force submodule-use for header-only deps (which is all but random123?). This isolates us and other builders/integrators from having to worry about version incompatibilities.

**Comment by brenthuisman** [comment]
Note that https://github.com/arbor-sim/arbor/issues/2147 is also open and undiscussed.

**Comment by thorstenhater** [comment]
I like to rely on as few things from external as possible, so I like the header-only approach.
That'll mean arbor-as-source is a bit bigger but if you have `arbor-x.y.z`, then you have `arbor-x.y.z`
not `arbor-x.y.z` minus some deps plus replacements for those provided by your OS.

Only potential issue would be linking arbor with symbols from, say, `fmt-X` into an application that also
links `fmt-Y`, but that should (!) be non-existent with a proper export hygiene.

**Comment by brenthuisman** [comment]
We need to figure out if people then linking Arbor and their own version of e.g. fmt can end up with clashing symbols.

**Comment by thorstenhater** [comment]
Done.
