### ISSUE TITLE
SIMD-enabled multicore should be a separate backend for catalogues

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1780]
# Introduction

This is a clean-up issue to make the use of externally built dynamic catalogues more robust.
It fixes a bug appearing when users build catalogues with a different SIMD configuration than
the Arbor library. It has already been observed as an artifact of multiple installs (eg pip over cmake)
and manifests as a crash. Currently we are blaming the user for a broken installation, which is not
sustainable.

# Proposed Fix

The ABI already separates the mechanism interface into metadata (`arb_mechanism_type`) and
callbacks (`arb_mechanism_interface`), where the latter provides a field `partition_width`. This
allows us to define multiple sets of callbacks for one mechanism. However, this is not exploited at
higher levels. Therefore 

- modcc: add a list of `arb_mechanism_interface` (one per SIMD width) instead of a single instantiation
- catalogues: allow registering those lists and querying by 'best match'; assuming the user wants the widest
   compatible vector by default, eg Arbor built with SIMD width 6 and the catalogue offers 1, 2, 4, 8, we return 2.
   In general the LCM.
- build-catalogue: build all compatible vectorisation schemes. This is a bit tricky, as we need to detect those.

# Extension to GPU

Similarly, for GPU support, we should allow having catalogues with HIP and CUDA, but I have no idea what havoc
that may cause with the linking.

**Comment by halfflat** [comment]
I'm not too keen on the complexity of a catalogue holding on to multiple implementations against the same interface and Arbor backend; could we instead solve (well, make less bad) the situation with adding an architecture field in the metadata that we can test for instruction set compatibility? 

In this scenario, trying to add a mechanism implementation to a catalogue for the CPU back-end would throw an (informative) error if the ISA was not compatible, but would quite happily cope with an implementation that otherwise used a shorter SIMD width than the maximum. In some circumstances (AVX512), the choice of a narrower width might be deliberate for better performance.

**Comment by thorstenhater** [comment]
The complexity is not that much, especially compared to the status quo. We already can (could?) have GPU and CPU implementations of the same interface. It's essentially stretching the idea of what an interface is.

**Comment by halfflat** [comment]
Currently we have one-to-one association between a back-end kind and an implementation, and any given cell group (for cable cells) is going to have a pointer to one or the other. Dispatch of cells to back-ends is determined by the domain decomposition, and when a user provides one, they just have to ensure that any catalogues have mechanism implementations for the cpu or gpu available.

With finer-grained back-ends, the domain decomposition back-end kind determination is more complex (for the heuristic in the default method, or for the user in their own processes), and the constraint on the catalogue is more severe: it must contain an implementation for any of the possible back-ends that might be end up in the domain decomposition. Negotiating this feels like it will be a headache.

I really think an ISA-compatibility assertion will get us most of the way there with much less complexity. A separate facility can be built using the catalogue methods to inquire if the available mechanisms are in a desired state, e.g. all ISA compatible (though this can be enforced at catalogue registration time), or that all the mechanisms are SIMD vectored to some minimum width, etc.

**Comment by thorstenhater** [comment]
Ok, I see the point, but I think since the selection returned from the catalogue will always be the same, we can work around it. Alternatively, we perform said selection at catalogue load time, so that the bijection persists, but catalogue can still be richer. What do you think?

**Comment by halfflat** [comment]
I still think it'd be simpler to keep the current arity of associations in any given catalogue, i.e. one name to one mechinfo; one name × back-end to one implementation. But what we could do is make it easier to assemble the catalogue you want from the catalogues you load, e.g.
```
     mechanism_catalogue the_cat(global_default_catalogue());
     mechanism_catalogue custom_cat = load_catalogue("magic_mechs.so"); // ISA compatibility checked in `load_catalogue`.
     
     the_cat.import(custom_cat, "custom."); // `import` also checks for ISA compatibility.
     the_cat.import(custom_cat, "", "special_mech"); // import just the one mechanism from `custom_cat` (mechinfo, and any implementations registered for back-ends; if it's a derived mechanism, import parents too, and complain if those are already defined in `the_cat`).
```
or
```
    auto my_simd_mech = custom_cat.get_implementation("special", arb_backend_kind_cpu); // returns clone of implementation
    assert(partition_width(my_simd_mech)==4); // let's be sure
    the_cat.register_impl("special", std::move(my_simd_mech));
    // or even:
    the_cat.register_impl("special", std::move(my_simd_mech), override_impl);
```
(new API bits above of course are malleable)

**Comment by thorstenhater** [comment]
The `name -> info` mapping would not be touched. What I envision would be this,
with Status Quo/Changes marked

ABI, will stay as is 
```cxx
typedef struct arb_mechanism_interface {
    arb_backend_kind   backend;               // GPU, CPU, ...
    arb_size_type      partition_width;       // Width for partitioning indices, based on SIMD for example
    arb_size_type      alignment;
    // [...] omitted for brevity
} arb_mechanism_interface;

typedef struct arb_mechanism_type {
    unsigned long             abi_version; 
    arb_mechanism_fingerprint fingerprint; 
    const char*               name; 
    // [...]
} arb_mechanism_type;
```

Implemenation header, made by `modcc`
```cxx
#pragma once

#include <cmath>
#include <arbor/mechanism_abi.h>

extern "C" {
  // static info, will stay
  arb_mechanism_type make_arb_default_catalogue_pas() {
    // [...]
  }

  // currently
  arb_mechanism_interface* make_arb_default_catalogue_pas_interface_multicore();
  arb_mechanism_interface* make_arb_default_catalogue_pas_interface_gpu();

  // should become this or similar (we might want to discuss where memory is allocated)
  void make_arb_default_catalogue_pas_interfaces(arb_mechanism_interface*, int* n_interfaces);
}
```
where `make_arb_XYZ_interfaces` should allocate an array of interfaces, fill it in, and return the
result back along with the count of filled values. Then, the loading side may do with that what it 
wants, based on the metadata in `arb_mechanism_interface` (which might need some more fields
some time in the future.)

Actually, it makes the whole affair a bit simpler, since can now ask questions like 
- Give me a GPU mech 
- Give me a CPU mech with SIMD >= 4
- Give me a CPU mech with SIMD compatible with width 4, ie 4, 2, 1

Note
- here we should take care to distinguish GPU by NV/HIP/...
- we also should check ISA/ABI compat

Into the catalogues we can put the result of these queries or fail with we cannot satisfy constraints.
So, catalogues remain untouched, but building them becomes a bit more interesting, since
we need to heed some constraints.

**Comment by halfflat** [comment]
> Into the catalogues we can put the result of these queries or fail with we cannot satisfy constraints.
> So, catalogues remain untouched, but building them becomes a bit more interesting, since
> we need to heed some constraints.

This is a better approach than changing the catalogue associations, I agree, but I still feel it is more complex than we need, and doesn't by itself fix the ISA mismatch leading to an illegal instruction crash problem that originally motivated the issue.

Also, when using modcc to build a mechanism, we would need to instruct it to build the widths/archs required, which absent some sort of cross-compilation or delayed compilation, are going to be limited to the capabilities of the architecture we're compiling on regardless. It would have limited utility in the circumstance where e.g. you're building on an avx512 architecture and want avx2 and avx versions too. With Anton looking at the SIMD library, we might have multiple widths for different ISAs (we can do that already, it's just a lot of code to write for little apparent gain), but then the question is: why build a 128-bit AVX2 SIMD implementation instead of a 256-bit one (say)?

It also puts the onus on the user or some heuristics added to the Arbor lib for choosing which version to add to the catalogue.

I still hope that the long term solution is compile on demand, especially if we can bear the cost of a runtime LLVM dependency, which will work nicely with arblang plans. In this picture catalogues will present a much, much simpler interface (none of this derived nonsense, for example!).
