### ISSUE TITLE
ImportError: cannot import name 'density' from 'arbor'

### ISSUE THREAD

**Issue by SteMasoli** [arbor-sim/arbor#1789]
Hi.

**Describe the bug**
>>> from arbor import density
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'density' from 'arbor'

**Context**
I'm using Mint 20.1 (Ubuntu based) and i have installed arbor (Version 0.5.2) using: pip3 install arbor. 
Than I tried to follow the tutorial at this [page](https://docs.arbor-sim.org/en/latest/tutorial/single_cell_detailed.html) but doing "from arbor import density" generates the "ImportError".

**Comment by noraabiakar** [comment]
The linked page is linked to our master branch. `denisty` is not part of release 0.5.2, it'll be in the next release. here's the relevant docs page for 0.5.2: https://docs.arbor-sim.org/en/v0.5.2/tutorial/single_cell_detailed.html

**Comment by Helveg** [comment]
This raises an interesting point: Maybe there should be a warning banner on `latest` like there is on all older versions?

**Comment by noraabiakar** [comment]
Good point. I agree.

**Comment by brenthuisman** [comment]
https://docs.arbor-sim.org redirects to the latest stable release, which is v0.5.2. There is/will be a more prominent indication, see top left at https://docs.arbor-sim.org/en/latest/. This version info will be shown in future stable releases as well, but not in v0.5.2, because it was merged after that release.

In any case, you will have to ensure yourself you are looking at the documentation for the version you're using.

@noraabiakar rtd generates for each push to master, no matter who wrote/merges the PR, and generates a 'release' with each tag. What is it you're trying to do?

**Comment by Helveg** [comment]
> In any case, you will have to ensure yourself you are looking at the documentation for the version you're using.

Most projects add these kind of banners to prevent misinformation, Arbor does it for all older versions of the docs too, why not add a similar banner that you're looking at bleeding edge docs?

**Comment by brenthuisman** [comment]
With v0.5.1 and v0.5.2 the info is missing, which is an oversight due to having a new theme. We cannot retroactively add the label to those versions due to the way readthedocs works (it interprets git tags as releases and generates from the tree in that tag, so we'd have to change what the tags point too, which is rewriting git history which is probably not a good idea).

We all though v0.6 would be out much sooner than it will be (mid Jan), when the version info is back next to the title. https://docs.arbor-sim.org/en/latest/ does show clearly you're looking at the latest info, right?

**Comment by Helveg** [comment]
Not for me no, there's no banner like on https://docs.arbor-sim.org/en/v0.5.1/

**Comment by brenthuisman** [comment]
Correct, but I explained that, right?

**Comment by Helveg** [comment]
So you're saying that this banner will be present on `latest`, like it is for `v0.5.1`, with a link to the last stable release?

![image](https://user-images.githubusercontent.com/28923979/146214274-fd656fac-a816-4f8d-944b-d3aa3847fdc2.png)

**Comment by brenthuisman** [comment]
Ah, you're saying the (newly added) version info is too subtle, and a big banner is needed?

**Comment by Helveg** [comment]
I was really hoping you had dug up some amazing extension that did that actually ;p

**Comment by brenthuisman** [comment]
Wait, no, it's not due to the theme, because v0.5.1 does show it too. It must be inserted by RTD then, and in that case it will be inserted for v0.5.2 when v0.6 is released.

However, there is not banner when you're on latest, alerting you that you're reading a 'non-stable' version of the docs. Is that the source for the confusion?

**Comment by Helveg** [comment]
Yep, and I've seen these kind of bleeding edge banners on some projects as well. They're definitely JavaScript extensions, they load later than the rest of the page.

**Comment by brenthuisman** [comment]
Sounds good. Want to make the PR?

@SteMasoli would such a warning have helped you?
