### ISSUE TITLE
Make `cable_global_properties` readable

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1802]
Like the `decor`, `cable_global_properties` is a one way bag, and what is put in can't be read out.

**Describe the feature you need**
Read operations of `set_property` and `set_ion`, and retrieving the catalogue one has registered.

**Explain what it is supposed to enable**
This is a problem for recipe composition (#1680). One can't read or merge the global properties of subrecipes.

**Additional context**
Arborio project needs to merge the recipe of the IO and CC

**Comment by llandsmeer** [comment]
This would be useful for example in the implementation of 'top-level' recipes that merge a set of recipes into a single recipe: https://gist.github.com/llandsmeer/83a50458ddb134eb87e94cd3c3a77b27
This was surprisingly easy to implement, except for the distribution of global_properties() -  because that function does not take a `gid` parameter.

**Comment by thorstenhater** [comment]
The catalogue now is a plain data member.
