### ISSUE TITLE
New wheels when minor Python version lands

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1808]
**Describe the feature you need**
New wheels when a new minor version of Python drops. The current release cycle could have us wait 3 months before we can update.

**Explain what it is supposed to enable**
Shiny new Python features.

**Comment by brenthuisman** [comment]
The wheels do not depend on minor Python versions afaik, so a rebuild of an Arbor tag should not have any changes and should work as is in a not yet released Python minor version.

Major Python versions is a good reason to trigger a rebuild, but given the frequency of those, I don't think our cycle is a problem.

Using shiny new Python features is also independent from Arbor, unless you mean keeping up with sugar that Pybind lets you add? In which case we need to code the things up because it makes sense to rebuild. Are there perhaps specific bits of sugar that you are looking to have?

**Comment by Helveg** [comment]
You cannot install Arbor's Python 3.9 tagged wheels with pip, so up until the release of Arbor 0.6 pip installing arbor would lead to the download of the source tarball and a local CMake build, which would fail in spectacular pip fashion with about 3 pages of red errortext :)

**Comment by brenthuisman** [comment]
Right, so that is the issue with major versions, and yes, I had noticed ;) So, with the 3 month cycle, the window of pain should be much shorter, but in the meantime, I don't know how I could trigger actions on the release of upstream Python major versions.

The wheel build does run monthly now too. I'm not sure if `uses: pypa/cibuildwheel@latest` is valid syntax, if so it might meet you halfway.

**Comment by Helveg** [comment]
```
3.9.0
M|M|P
a|i|a
j|n|t
o|o|c
r|r|h
```
right? Just so we're talking about the same things

**Comment by Helveg** [comment]
You could run a daily workflow, check the cpython tag feed https://github.com/python/cpython/tags.atom and run the feed if there's a tag in there for that day? :)

**Comment by brenthuisman** [comment]
Whoops, I forgot there is actually a 3 ;) With major I meant minor.

Do they tend to add wheels for (package) versions already released?

**Comment by brenthuisman** [comment]
1. Are you sure? You can't overwrite release artifacts on PyPI, and although you can append (add a wheel for a new Python version) I've never seen that in action. E.g. `numpy` never has. Have an example? 
2. We do not do testing of `stable` and `old-stable` releases. I've thought that there may come a time when we should, but that that time has not come yet. It's a bit of work, and AFAIK all Arbor users are on `master` or  `stable`. If and when users require specific Arbor versions, we have been thinking that we should advise them to use Spack, because then there is control over the entire configuration.

**Comment by Helveg** [comment]
1. numpy releases new patch versions for each release (3.19 = 1.21.3, 3.9 was 1.19.3) but they're usually slow because of the complexity and review process. I don't think anyone amends existing releases, I didn't even know that was possible :D
2. This isn't about having a specific Arbor version, it's about having _any_ Arbor version available, worst case is Python 3.11 drops a day after Arbor 0.8 then we'd all have to wait 3 months with upgrading, include any Python tools that depend on you.

**Comment by brenthuisman** [comment]
1. Right, we could release Arbor upon Python minor releases. However, between v0.5 and v0.6 was a year, so in my view 3 months release cycles are already a huge improvement ;)
2. There is always the option to build :) I think that if we know a new minor is dropping within a few weeks or so, we can and will certainly wait for a while to make sure we generate wheels for the new version. I think we are safe until october with our current schedule: https://www.python.org/dev/peps/pep-0664/ I'll make a note to remember to time the cycle with that date as much as possible.

**Comment by Helveg** [comment]
Great! If the Python minor release are considered in the release cycle, and wheels released within a month or so then I think Arbor is keeping up with the community conventions :) Thanks!
