### ISSUE TITLE
Allocating the same GPU on multiple processes leads to `RuntimeError: GPU memory` error

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1895]
**Describe the bug**
When multiple Arbor processes target the same GPU, i.e. 2+ arbor processes on the same hardware unit create an `arbor.context` with an `arbor.proc_allocation` that targets the same `gpu_id`, the following error occurs:

```
Traceback (most recent call last):
  File "/users/bp000347/arbenv/bin/bsb", line 33, in <module>
    sys.exit(load_entry_point('bsb', 'console_scripts', 'bsb')())
  File "/users/bp000347/arbenv/bsb/bsb/cli.py", line 26, in scaffold_cli
    start_cli()
  File "/users/bp000347/arbenv/bsb/bsb/cli.py", line 255, in start_cli
    scaffoldInstance.run_simulation(cl_args.simulation, quit=True)
  File "/users/bp000347/arbenv/bsb/bsb/core.py", line 386, in run_simulation
    simulation, simulator = self.prepare_simulation(simulation_name)
  File "/users/bp000347/arbenv/bsb/bsb/core.py", line 419, in prepare_simulation
    simulator = simulation.prepare()
  File "/users/bp000347/arbenv/bsb/bsb/simulators/arbor/adapter.py", line 456, in prepare
    simulation = arbor.simulation(recipe, self.domain, context)
RuntimeError: GPU memory:: gpu_malloc unable to allocate 322812 bytes: all CUDA-capable devices are busy or unavailable
```

There are several problems:

* This seems like an entirely preventable error: Don't allow arbor processes to target the same GPU, you have all information in the `arbor.context` to figure out this will happen, and to prevent it. Some mention of this restriction in the docs on hardware allocation would also be good.
* The error does not contain enough information to point to a cause, who knows why the CUDA device is busy or unavailable, users will probably be unaware that they double-booked their GPU:
  * The call stack trace ends in `arbor.simulation`, no deeper CPP information is captured (see #1896)
  * The error message is a non-descript message, presumably raised by nvidia, uncaught, wrapped by pyarb and reraised
* Because the error is gobbled up by pyarb, there's no straightforward (or documented by Arbor) way to interrupt at the point where the error occurs. (see #1897)

**Comment by bcumming** [comment]
This is very difficult to enforce in practice, particularly when MPI is involved.
The rub is that it is actually very challenging to determine if two MPI ranks are "seeing" the same GPU without matching GPU unique identifiers and global MPI communication. This requires synchronisation, which would likely end up with errors getting thrown during model instantiation, much later than the offending MPI and GPU contexts were created (one of @Helveg 's pet peeves ;) ).

Arbor's C++ arborenv library provides a helper that performs the related task of assigning a unique GPU to each MPI rank, if possible:
https://docs.arbor-sim.org/en/latest/cpp/hardware.html#_CPPv4N6arbenv16find_private_gpuE8MPI_Comm

We could expose this via the Python API?

FWIW, the algorithm that performs this was fun to write, and more complex than you might first assume, and is something that has to be used with care because of the MPI synchronisation under the hood).

**Comment by Helveg** [comment]
re the pet peeve: yes, annoying, but in this case it can only come from 1 source, the `context` that is used in the `simulation` call. With a good error message that explains what that source is, I think it can be clear enough even when the error happens at a later point

**Comment by thorstenhater** [comment]
Hi,

I am not sure this is a general issue, using one GPU from multiple processes is usually ok and I have done so successfully (alas via MPS). That said, we can expose the private GPU helper.
