### ISSUE TITLE
Document a debugging procedure

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#1897]
**Describe the feature you need**
I'm not a proficient debugger and @thorstenhater has to feed me `gdb` commands every time. Errors are often captured in a not so useful manner (see #1896 ) and `gdb` doesn't stop on these "handled" exceptions. I'm sure a method must exist for whatever mechanism that now transforms these errors into Python `RuntimeError`s, to leave a breadcrumb for debuggers to pick up on.

Then, please document in popular debuggers such as `gdb` or `valgrind`, how to have the debuggers pick up and interrupt on this breadcrumb.

**Explain what it is supposed to enable**
Interrupting arbor on critical failure points, so that the state of arbor can be inspected, and more useful debugging information can be provided in complex situations where creating an MRE is not feasible.

**Additional context**
See #1895

**Comment by thorstenhater** [comment]
:wave: 
As pointed out elsewhere, there is not much I can do for you. Debugging with GDB or otherwise is not really
an exact science we can formularise. I can only recommend (for all developers) to familiarise yourself with GDB or
lldb. They have options to catch exceptions and halt on certain conditions/locations. The rest is working with the
code and following the leads.

Also, C++ does not provide stacktraces and there are no portable facilities exist for adding them. On _Linux_ 
however we do use libunwind when installed. I added an extra field to `arbor_exception` (`where`) which 
is a string containing the stacktrace (iff enabled, that is) in this PR. You could take a look and tell me if it works
for you and is helpful in your efforts (also in #1930 or #1896). Binding `arbor_exception` and inspecting the 
extra data is left to the user as an excercise :)

Currently it's a simply a string to check the soundness and whether it's useful at all, but if we find it worth the effort
and identify a suitable cross-platform stacktrace library, this can be changed.

**Comment by Helveg** [comment]
OK
