### ISSUE TITLE
Simultion progress bar doesn't update if there are no spikes in the network

### ISSUE THREAD

**Issue by llandsmeer** [arbor-sim/arbor#2089]
Inside the Jupyter notebook environment in the EBRAINS Colaboratory, using `sim.progress_banner()` doesn't result in a interactive progressbar during the simulation. Instead, it stays at 0% the entire simulation time then jumps to 100% when finished. 

Relevant function is [epoch_progress_bar](https://github.com/arbor-sim/arbor/blob/master/arbor/simulation.cpp#L591). I suspected it would be a missing stdout flush, but there is a `fflush(stdout);` call at the end of the iteratively called function..

**Comment by llandsmeer** [comment]
Ipython notebook

**Comment by llandsmeer** [comment]
With some new insights (due to @thorstenhater) this is probably due to the absence of spikes in the network - the progress banner only updates when there are spikes

**Comment by bcumming** [comment]
The progress bar is updated at the end of each epoch.

Any model with no connections (e.g. multi cell models where the only connections are gap junctions, or single cell models) will have only one epoch (because there is no need to exchange spikes).

Adding support for updating the progress bar from within an epoch would be quite tricky for the generic case, though it the special case of single cell models would be fairly straightforward, if a little hacky.

**Comment by thorstenhater** [comment]
This has been touched in some and I wouldn't be keen on sacrificing performance (by cutting epochs artificially short),
thus I consider this a 'wont fix'.
