### ISSUE TITLE
Segmentation fault adding multiple mpoints

### ISSUE THREAD

**Issue by SteMasoli** [arbor-sim/arbor#2123]
Arbor 0.8.1
Single cell.

arbor.config()
`{'mpi': False, 'mpi4py': False, 'gpu': None, 'vectorize': False, 'profiling': False, 'neuroml': True, 'bundled': True, 'version': '0.8.1', 'source': '2022-12-22T15:48:03+01:00 28129e032a9dfef45568aea6697f995b4821cbbe', 'arch': 'none', 'prefix': '/project/_skbuild/linux-x86_64-3.10/cmake-install', 'binary_path': 'bin', 'lib_path': 'lib64', 'data_path': 'share', 'CXX': '/opt/rh/devtoolset-10/root/usr/bin/c++', 'pybind-version': '2.10.1'}`

**Describe the bug**
I'm trying to build a custom axon, composed by multiple sections and to do it faster I'm using a for cycle.
The code crashes with a segmentation fault.

In another model I have multiple sections defined line by line and they work fine.

**Context**
The minimum code to replicate the issue. 
The morphology can be taken from [(https://senselab.med.yale.edu/ModelDB/showmodel.cshtml?model=265584&file=/Granule_cell_2020/01_GrC_2020_regular/morphology/#tabs-2)]

```
import arbor
from arbor import density, mechanism as mech
from arbor import location as loc

tsim = 1000

asc = arbor.load_asc('morphology/GrC2020.asc')
tree = asc.segment_tree

tree.append(0, arbor.mpoint(0.0, 0.0, 0.0, 0.7), arbor.mpoint( 0.0, 1.0, 0.0, 0.7), tag=2)
tree.append(1, arbor.mpoint(0.0, 1.0, 0.0, 0.35), arbor.mpoint(0.0, 18.0, 0.0, 0.35), tag=2)

num_start = 18
for i in range(0,18):
    tree.append(2+i, arbor.mpoint(0.0, float(num_start + (7*i)), 0.0, 0.15), arbor.mpoint( 0.0, float(num_start + (7*(i+1))), 0.0, 0.15), tag=2)

labels = arbor.label_dict()

labels['all'] =         '(all)'
labels['soma'] =        '(tag 1)'
labels['axon'] =        '(tag 2)'
labels['dend'] =        '(tag 3)'


decor = arbor.decor()
cell = arbor.cable_cell(tree, decor, labels)
model = arbor.single_cell_model(cell)
model.run(tsim)
```

**Comment by thorstenhater** [comment]
So, I _think_ (hard to tell without insight into the model) the tree building is still off.
Your segment tree already has segments 0, 1, 2, ... 29; make that visible by adding
some print statements
```py
asc = A.load_asc('morphology/GrC2020.asc')
tree = asc.segment_tree

print(tree.size)
```
prints `30` here. Segment `0` is by definition the first one added (_usually_ interpreted as the soma)
When you now attach to `0` this segment will have `id=30`, thus if your axon is meant to extend linearly
from the soma, you'll need to attach the next one to `parent=30`. Conveniently, `tree.append` return the
id of the new segment. Thus the tree building becomes a bit more simple
```py
parent = 0 # the soma
parent = tree.append(parent, arbor.mpoint(0.0, 0.0, 0.0, 0.7), arbor.mpoint( 0.0, 1.0, 0.0, 0.7), tag=2)
parent = tree.append(parent, arbor.mpoint(0.0, 1.0, 0.0, 0.35), arbor.mpoint(0.0, 18.0, 0.0, 0.35), tag=2)

num_start = 18
for i in range(0,18):
    parent = tree.append(parent, arbor.mpoint(0.0, float(num_start + (7*i)), 0.0, 0.15), arbor.mpoint(0.0, float(num_start + (7*(i+1))), 0.0, 0.15), tag=2)
```
Since the axon is a linear chain of the same radius after the first three, you could also write
```py
parent = 0 # the soma
parent = tree.append(parent, arbor.mpoint(0.0, 0.0, 0.0, 0.7), arbor.mpoint( 0.0, 1.0, 0.0, 0.7), tag=2)
parent = tree.append(parent, arbor.mpoint(0.0, 1.0, 0.0, 0.35), arbor.mpoint(0.0, 18.0, 0.0, 0.35), tag=2)
parent = tree.append(parent, arbor.mpoint(0.0, float(18 + 7*0), 0.0, 0.15), arbor.mpoint(0.0, float(num_start + 7*1)), 0.0, 0.15), tag=2) # this one is still tapered
parent = tree.append(parent, arbor.mpoint(0.0, float(num_start + 7*1), 0.0, 0.15), arbor.mpoint(0.0, float(num_start + 7*17), 0.0, 0.15), tag=2) # this summarizes all segments with a constant radius
```
**unless** your discretisation is `every-segment`. Arbor doesn't care about thee segments after the morphology
is constructed from the segment tree.

It might be helpful to construct your morphology and dump it to `acc` which you can inspect visually in our GUI.

**Comment by Helveg** [comment]
@SteMasoli I assume here you are constructing the ascending axon and parallel fiber of the granule cell, right? You need to appenbd only 3 segments in the tree: 1 for the entire AA, 1 for the entire left fork of the PF, and one for the entire right fork of the PF;

Arbor takes care of discretizing that into the "sections" and "segments" that you are used to in NEURON. If you wish to have fine grained control over the discretization, you can do this by changing the "discretization policy". Here is the conceptual explanation: https://docs.arbor-sim.org/en/latest/concepts/morphology.html#discretisation-and-cv-policies

And here the Python API: https://docs.arbor-sim.org/en/latest/python/morphology.html#discretisation-and-cv-policies

**Comment by thorstenhater** [comment]
From private communications I think we'll need to clarify this further. As suggested, I'll try to use an ASCII cartoon here.
It's also quite a bit of text, sorry for that, but I hope it helps. Here we go.

There still seems to be some lack of clarity wrt the segment tree semantics.
Let's start with some terms that might be used differently or not at all in
other tools.
- segment :: ground unit of the morphological construction process comprising
  two end points and their radii, ie a conical frustrum. Also has a tag (a la
  SWC) and an id (unsigned number) attached. Must be unbranched and cannot be split further, thus
  if you need to attach to the middle, add two segments instead.
- branch :: a continous, non-branched part of the morphology, due to the
  definition above a list of segments where each element is the parent of the
  next. Not necessarily consecutively numbered.
- section :: not used in Arbor
- region :: a subset of a morphology with a finite measure, ie an area.
- locset :: a subset of a morphology with a vanishing measure, ie a set of points.
- compartment :: subset of a branch, constructed by the FVM discretisation. We
  usually prefer _control volume_ (CV) since that is the FVM term. And shorter.
  Note that the way the tree/morphology were constructed have no impact on the 
  layout of CVs _unless_ you specifically enforce it.

So, now to the _segment tree_ as the name suggests, a tree made out of segments.
Since each segment has an id, we can easily record each segment's parent and the
tree structure guarantees there is at most one and except for the root (which
has parent `nil` or `mnpos`) exactly_ one. This brings us to the problem at
hand. Consider this to be the segment tree obtained by loading the ASC (or any
other format) file
```
                   -- 6 --
                  /
-- 0 -- * -- 1 --*-- 4 -- -- 8 --
         \
          -- 2 -- -- 3 -- -- 7 --
```
I marked segments as `-- id --` and branch points as `*`. Observe that ids 0-8
are used and that the numbering may jump around a bit, but the parent id is
always _smaller_ than the child id. Assuming segment 0 is the soma, we can start
adding our axon. Assume three segments to be added. As said before, adding a
segment requires the endpoints, a tag, and the parent segment. Let's try it the
way you opened the issue with
``` python
for p in range(3):
    tree.add(p, ...)
```
this would give us this new picture
```
          == 9 ==   -- 6 --
         /         /
-- 0 -- * -- 1 -- * -- 4 -- -- 8 --
         \         \
          \          == 10 ==
            -- 2 -- * -- 3 -- -- 7 --
                     \
                       == 11 ==
```
since the parent ids are 0, 1, 2. Newly added segments are marked `== id ==` for
emphasis. I assume that is not what you want, but I hope it has become clear _why_
it happens. If not, please ask.

Now let's try the other way. I'll refrain from using a loop for clarity
``` python
p = 0                 # the soma
p = tree.add(p, ...)  # add first segment
# at this point p is 9, the id of the newly added segment
# and the size of the tree before adding the last segment.
p = tree.add(p, ...)  # add next segment
p = tree.add(p, ...)  # add next segment
```
this would give us this tree
```
           == 9 == == 10 == == 11 ==
          /          -- 6 --
         /         /
-- 0 -- * -- 1 -- * -- 4 -- -- 8 --
         \
           -- 2 -- -- 3 -- -- 7 --
```
which is probably closer to your intentions. 

For more convenience though, you can try our segment tree manipulation API:
```python
# Load morph from disk
asc_tree = A.load_asc('morphology/GrC2020.asc')
tree = asc.segment_tree

# Make axon independently
axon = A.segment_tree()
for p in range(3):
    axon.add(p, ...)

# Now graft axon onto the original tree at the soma
tree.join_at(0, axon)
```

Finally, note that this is a tree representation, not a 3d rendering, so extents 
and directions have no real meaning. However, if you need to attach to a specific
_end_ of the soma, you'll need to split the soma into multiple parts (rooted at a 
zero size segment for utmost precision) extending in different directions and 
attach dendrite and axon to the opposite ends.

As I said, that's a lot of text to go through, but I hope it helps.
