### ISSUE TITLE
Math not rendering in docs

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#2227]
Looks like https://docs.arbor-sim.org/en/latest/concepts/lif_cell.html#lifcell isn't rendering the math

**Comment by thorstenhater** [comment]
This seems to be a global problem and even occurs in local builds of the docs. Investigating...

**Comment by thorstenhater** [comment]
It seems that the URLs for the embedded JS are off. In particular, opening the dev console turns up a series 
of errors like this:
```
GET | https://docs.arbor-sim.org/en/latest/concepts/_JavaScript('/_/static/javascript/readthedocs-doc-embed.js',%20priority=500,%20async='async') 404
```

**Comment by Helveg** [comment]
The RTD search also seems broken, do you notice problems as well? Mine doesn't load any results any more

**Comment by thorstenhater** [comment]
The only thing I could find is this:
https://stackoverflow.com/questions/68709496/searching-takes-forever-on-readthedocs-when-the-phrase-is-not-present-on-th
which has some of the same symptoms as we observe. The fix was to bump `sphinx-rtd-theme`.
_Our_ current theme is a patched and hardcoded version of `divio` that @brenthuisman added two years back.
So, we might be forced to bump this.

**Comment by thorstenhater** [comment]
Indeed, switching to a different theme fixes both problems.

**Comment by Helveg** [comment]
The `furo` theme is pretty nice https://github.com/pradyunsg/furo

**Comment by thorstenhater** [comment]
Guess which one I switched to.
