### ISSUE TITLE
Support high-level network model specification

### ISSUE THREAD

**Issue by lkoelman** [arbor-sim/arbor#418]
Besides setting up individual cell models, I need an easy way to set up a large network model consisting of multiple population of cells with different inter-population and intra-population connectivity rules, and population properties.

The high-level specification of network models can be abstracted away from the underlying simulation engine, and has so far been addressed by two software packages I know of: the Allen Institute's [BMTK](https://github.com/AllenInstitute/bmtk) ([docs](https://alleninstitute.github.io/bmtk/index.html)) and [NetPyNE](https://github.com/Neurosim-lab/netpyne) ([docs](http://www.neurosimlab.org/netpyne/overview.html)) developed by the people at SUNY's neurosimlab. They are both wrappers around NEURON (and NEST in the case of BMTK) and attempt roughly the same thing, with similar features ([list of key features](http://www.neurosimlab.org/netpyne/overview.html#major-features)). I spoke to one of BMTK's developes at the SfN 2017 conference, and he mentioned they were in talks with the NetPyNE developers to work toward common data formats.

I suggest that support for these high-level network definition packages is facilitated in Arbor by looking at what sort of Python functions they would require, and exposing similar or equivalent functions in Arbor's Python interface.

**Comment by bcumming** [comment]
Arbor uses recipes to describe models, which take a very "cell-centric" view of a model.

A recipe provides an interface that can be queried about the properties of a cell.

For example:

```C++
class my_recipe: arb::recipe {
    // implement arb::recipe interface
};

// create one of your recipes
my_recipe rec;

// get the "kind" of cell 23, which could be one of multicompartment cell,
// poisson spiking cell, regular spiking cell or LIF cell

auto k = rec.get_cell_kind(23);

// get a description of cell 23 (wrapped in a std::any (see C++17) style wrapper
// that can hold any type of cell description
util::any desc = rec.get_cell_description(23);

// get a list of all network connections that terminate on cell 78 (i.e. have
// post-synaptic sites on cell 78) 
auto cons = rec.connections_on(78);
```

The motivation behind this design is to simplify parallel model building. Consider when all the cell gid have been divided up over all the MPI ranks, so that each rank has a list of gid for which it is responsible. Then an MPI rank can query the `my_recipe` for information about only the cell `gid` that it is respobsible for.

Ideally, the author of `my_recipe` can write the recipe to lazily generate the information about `gid` when requested. That way each rank generates only the information required to describe its part of the model, with no need to communicate with other ranks. For fully parameterized models, this should be possible, though models based on reading in connectivity and population information from observations will not be so straightforward. 

Any interface to packages like BMTK or NetPyNE would wrap an recipe around the package. How neatly they can work with this "cell-centric", I don't know! Though I think that this is how such packages have to work to build really large models inside a distributed simulator "on the fly".

**Comment by w-klijn** [comment]
Late to the party:
I have integration of CSA (1) on my radar this in combination with NeuroML (2) should cover the majority of use-cases. This combination is already in use with NEST and would fit in a larger road-map.

1) https://www.ncbi.nlm.nih.gov/pubmed/22437992
2) https://www.neuroml.org/

**Comment by thorstenhater** [comment]
Thanks @w-klijn for the suggestions, I have read the CSA paper and looked into the NML-style population/projection based approach.

To solve this issue for Arbor, I will suggest a DSL in the style of the ones we already use for regions, locsets, and CV policies.
It remains to be designed, though, and I can best imagine following the NML approach with that. We will put out this ticket as a project to be offered to interested students and/or postdoc, depending on interests and chosen scope. A project description is quoted below.

> We aim to design a high-level, declarative specification of network connectivity for use in simulations of morphologically detailled neurons. In particular, such a description should take the form of a domain-specific language (DSL) and an implementation in Arbor [1]. The project includes a study of the design space and prior art, as well as the use of connectivity rules in existing simulators and the requirements of neuro-scientists. From this a model should be developed that captures practical users' needs while building upon a composable structure.
1. https://github.com/arbor-sim/arbor
2. https://www.ncbi.nlm.nih.gov/pubmed/22437992
3. https://www.neuroml.org/

**Comment by thorstenhater** [comment]
Since the discussion about the design already started offline, I will put my vague ideas into some words.

# Introduction

Arbor has to deal with two kinds of connections:
- bi-directional instanteneous dendrite -> dendrite (Gap Junctions)
- uni-directional delayed axon -> dendrite (Synapses)

# Status Quo

Currently, connections are constructed using recipe callbacks by use of explicit numeric global ids (`gid`s).
The specifics aim at efficiency and generality via general callbacks and lazy construction. 

## Gap Junctions
Gap Junctions are created in two steps:

1. Assign a `gap_junction_site` with a label `lbl` to a locset `ls` of a cell. This is done in the cable cell/decor.
2. Declare connections as (essentially) pairs of `((gid, lbl), (gid', lbl'))` connecting gap junctions between different cells. This is returned via callback `gap_junctions_on` from the recipe.

Since this is a bi-directional connection, both partners must setup symmetrical connections.
Note that this is important, since locsets may be of cardinality > 1.
GJ connections maybe assigned parameters and (soon) mechanisms.

## Synapses

Creation of synapse connections also comes in steps, but since they are directed and all downstream cells receive action potentials from a source it is slightly different.

1. On the source cell with `gid` add a `threshold_detector(limit)` to  a locset `ls`.
2. On the target cell add synapse to a locset `ls'` giving a label `lbl'`
2. On the target cell with `gid'` declare an incoming `connection` as `(gid, ls, lbl')`.

Again, parameters and mechanisms apply.

# Evolution into a Declarative DSL

We start by setting the goals of this design

- Extensible: It should be easy to add new primitives.
- Composable: It should be easy to take two existing descriptions and add connections between them.
- Backwards compatible: We should be able to express the current architecture in the new design.
- Declarative: We should eschew explicit indices

## A Proposal

We observe that a lot of the information above can be generated or inferred from a higher level description. To reduce the connection mechanism to its bare essentials, two _populations_ of cells are connected on a set of _locations_ using a _connection kind_. So, the highest level primitive should reflect that [1]

```LISP
(connect (source pop ls) (target  pop' ls') kind policy)
```

Additionally, we need to set up a fourth argument `policy` that describes _how_ the connections should be formed.
From here, we can see that we need to design sub-DSLs for describing

1. populations
2. connection kinds
3. policies

Locsets are already part of Arbor's set of DSLs and can be given here as either inline expressions or references.

### Populations

Populations are built using set arithmetic and predicates, a few ideas
- `all`: all cells
- `cell-kind? type set`: select cells by their cell kind
- `difference`, `union`, ...: set operators
- `tag? tag`: allows to select by meta-data/tags. Tags need to be added to Arbor.
- `distance-lt (x, y, z)`: Allow to query by meta-data/position. Example for a whole class of spatial queries.
- `has-mechanism? name`: Implicitly differentiate cell types by mechanisms
- `has-locset? label`: Useful for picking suitable locsets to connect to

Espite the earlier dislike for explicit indices, we could imagine this to be useful `(gids gid0 gid1 ...)` at least for simple setups and backwards compatibility.

### Connection Kinds

These simply define connections and their parameters. The corresponding item will be implicitly added to the cell model.
- `gap-junction mech params`: Set up a symmetric connection, adding sites to the model
- `synapse mech params`: Set up directed connection, adding spike detectors and synapses

Open question: (How) do we allow varying parameters?

### Policies

The most important and most vague part, since it depends a lot on the modellers' needs. So far, we ignored the mapping between the sets of locations to be connected. By Arbor's design each such point (on a CV) can be identified by the cell's `gid`, the `locset`, and an offset `lid` into the locset's multi-set of points. When connecting two such multi-sets given by `(gid, ls)` we need to define how to map points to points. This is especially important for gap junctions. By nature of the problem, we need to define the mapping in two levels as cell to cell and id to id.

Open question: Do we _need_ id -> id mappings? It could be resolved by refining locsets.

Again a few ideas on how to describe such mappings, which might be useful at one or both levels
- `round-robin` select cyclically
- `all-to-all`
- `take n` select first `n`, failing with an error if not fufillable.
- `stochastic p` select with probility `p`, if `p=nil` choose uniformly
    NB We imagine that `p = exp(-dist(src, tgt))` could be a high value addition
- `unique` discard duplicate connections
- `no-loops` discard connections to self
- `random f t` a random integer between `f` and `to`

**Many** extensions to this list can be imagined, so let this serve as a example and extend by need.

As an example how these could be used:

We want to define connections such that each source cell has exactly 
100 unique, non-self connections selected randomly from the potential
target cells. This is not describing how to map ids.

```LISP
(policy (all) ; sources
            (take 100 (unique (no-loops (stochastic (all)))))) ; target per source
```

[1] I am following Arbor's style of s-exp DSLs here for consistency. Especially policies though could benefit from simpler pipelining, eg `take 100 | unique | ...`.

**Comment by Helveg** [comment]
Small note: I'd love a mix of s-expressions and pipelines! Could simplify and clarify a lot of operations
