### ISSUE TITLE
Atomise time

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#543]
`time_type` represents time points in Arbor. For now, `time_type` is `float`, which is just about acceptable for simulations with times reasonably measured in seconds.
However, we run into rounding errors for simulations measured in hours/days.

An ideal solution would be to represent times as unsigned counts of some atomic time unit, aka a "jiffy".
If using a nanosecond jiffy:
*  a 64 bit unsigned integer can represent time periods of hundreds of years.
* a 32 bit unsigned integer can represent intervals of 4 seconds

**Comment by halfflat** [comment]
This is how I understand the design parameters:
* `float` was chosen over `double` primarily because of memory utilization.
* A general time representation should be able to accommodate negative values (we need to represent differences in absolute time), so a 32-bit int can represented circa. 2e9 jiffies if we go with a fixed point representation, which is a bit small for a 1 ns jiffy.
* A jiffy will bound below some of our numerical errors; with phenomena at the scale of circa 100 µs, a 1 ns jiffy gives us roughly a 1 in 1e-6 error — it seems 1 ns is probably the largest jiffy we could justify.

I think this means that we either use a 64-bit time representation everywhere (fixed point or double precision floating point) or we essentially used a mixed precision: e.g. `time` and `time_to` are kept as 32-bit offsets to epoch start, and `dt` then also 32-bit; event times in queues though then need to be manipulated at merge to adjust epoch offsets.
