### ISSUE TITLE
Add interface for accepting spikes from an external source

### ISSUE THREAD

**Issue by bcumming** [arbor-sim/arbor#626]
Take the interface and implementation that was written for the hackathon.

https://github.com/arbor-sim/arbor/tree/spike-external

**Comment by halfflat** [comment]
Having a look at what is required, I believe we need:
* The `external_connections_` code in `communicator.hpp` (though I would keep the source unsigned).
* `external_spike_callback` in `simulator` and implementation class.
* Customizable `min_delay` — though I think this should be done at `simulator` initialization time rather than after.
* The `make_event_queues` overload in `communicator`.

I'd dearly like a less strongly-coupled solution for external spike exchange based on e.g. moving windows over per-simulator bundles of generated spikes and dynamic integration window size, but that's another story.

**Comment by halfflat** [comment]
Oh, and I think we should extend the `external_spike_callback` interface so that it takes an argument for the minimum window of external events, i.e. a `t` such that any subsequent call to the callback provides events with time not less than `t`.

We can check that assertion and throw an error indicating desynchronization.

**Comment by halfflat** [comment]
Might be a stretch goal, but I'd like to see this interface in the 0.2 release; adding the tag and we'll see how we go.

**Comment by halfflat** [comment]
Removing 0.2 tag; will aim for 0.3.

**Comment by thorstenhater** [comment]
🎉 closed by #2001
