### ISSUE TITLE
GPU Build Fails with GCC 7.3.0 CUDA 9.2 CMake 3.12.3

### ISSUE THREAD

**Issue by AndiH** [arbor-sim/arbor#645]
As discussed via email, I'm reporting a problem I have with building the GPU version of Arbor with the following dependencies on JURECA

* GCC/7.3.0
* CUDA/9.2.88
* CMake/3.12.3
* MVAPICH2/2.3-GDR
* Some notes: GCC 7.3.0 is currently the oldest supported GCC on JURECA. Because of the -GDR version, MVAPICH2 is currently the preferred MPI implementation to be used together with GPUs; it (used to/) is supposed to have the best performance for CUDA-aware MPI calls.

I configure with

```
cmake ../src -DARB_WITH_GPU=ON -DARB_ARCH=haswell -DARB_VECTORIZE=ON -DARB_WITH_MPI=ON -DCMAKE_C_COMPILER=`which mpicc` -DCMAKE_CXX_COMPILER=`which mpicxx`
```

The issue reads the following

    [100%] Linking CUDA device code CMakeFiles/ring.dir/cmake_device_link.o
    nvcc fatal   : Unknown option 'pthread'

It seems to be related to `-pthread` being passed as a direct flag to `nvcc`, even though it's suppose to be passed to the underlying host compiler – see https://gitlab.kitware.com/cmake/cmake/issues/18008.

Using `make VERBOSE=1` to extract the failing line and then manually entering the corresponding directory and calling the same line,

* plus `-Xcompiler` in front of the `-pthread` option, or
* without `-pthread` altogether

seems to solve the issue.

```
make ring bench VERBOSE=1

OUTPUTOUTPUTOUTPUTOUTPUT…

cd /homeb/zam/aherten/NVAL/ICEI-Benchmarks/Arbor.jureca/src/arbor/build/example/ring && /usr/local/software/jureca/Stages/2018b/software/CMake/3.12.3-GCCcore-7.3.0/bin/cmake -E cmake_link_script CMakeFiles/ring.dir/dlink.txt --verbose=1
/usr/local/software/jureca/Stages/2018b/software/CUDA/9.2.88/bin/nvcc  -O3 -DNDEBUG -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink CMakeFiles/ring.dir/ring.cpp.o -o CMakeFiles/ring.dir/cmake_device_link.o ../../lib/libarbor.a ../../lib/libarboraux.a ../../lib/libarbor.a -pthread -lcudadevrt -lcudart_static -lpthread -ldl
nvcc fatal   : Unknown option 'pthread'

cd /homeb/zam/aherten/NVAL/ICEI-Benchmarks/Arbor.jureca/src/arbor/build/example/ring

/usr/local/software/jureca/Stages/2018b/software/CUDA/9.2.88/bin/nvcc  -O3 -DNDEBUG -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink CMakeFiles/ring.dir/ring.cpp.o -o CMakeFiles/ring.dir/cmake_device_link.o ../../lib/libarbor.a ../../lib/libarboraux.a ../../lib/libarbor.a -Xcompiler -pthread -lcudadevrt -lcudart_static -lpthread -ldl

OR

/usr/local/software/jureca/Stages/2018b/software/CUDA/9.2.88/bin/nvcc -O3 -DNDEBUG -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink CMakeFiles/ring.dir/ring.cpp.o -o CMakeFiles/ring.dir/cmake_device_link.o ../../lib/libarbor.a ../../lib/libarboraux.a ../../lib/libarbor.a -lcudadevrt -lcudart_static -lpthread -ldl
```

I can do some more tests, on my to do list is:

* Use another MPI instead of MVAPICH GDR (@apeyser's idea, indirectly)
* Use another CMake
  - 3.13.0-rc3
  - 3.12.0

It could be Monday before I'll look at it again, though.

**Comment by halfflat** [comment]
CMake is definitely doing something odd here — even more odd than passing `-pthread` to `nvcc`.

1. It runs the device linker, despite the fact that we do not set the `CUDA_SEPARABLE_COMPILATION` property: there should be no need for a device linking pass in this circumstance.
2. Regardless, the device linking pass is performed for the _executables_ linking against the library, instead of for the library itself. Even if we did have separable compilation enabled for the library, this would only make sense if the other sources for the executable included CUDA code that could be passed to the library e.g. as callbacks, in which case (as I understand it) it too would require the `CUDA_SEPARABLE_COMPILATION` property be set.

The simplest CMake 3.12 fix seems to be change the `THREADS_PREFER_PTHREAD_FLAG` variable from  `ON` to `OFF` in the top level CMakeLists.txt file (line 70 in current master #0b7f88cad92a446fa8eb135a56fd51572432ba84).

I'm in the process of making some minimal demos of the above issues (and another, regarding installation) that I can make into issues for CMake.

**Comment by halfflat** [comment]
Turns out (gosh I love the CMake documentation) there is a property `CUDA_RESOLVE_DEVICE_SYMBOLS` that can be set on a static library target that will ask cmake to do the device linking on the library, rather than on the thing to which it is linked (despite the fact that device linking isn't necessary in the first place). Trying it out.

**Comment by AndiH** [comment]
Thanks for looking into it! Let me know if I should test something!
