### ISSUE TITLE
Update Arbor documentation for 0.2 release.

### ISSUE THREAD

**Issue by halfflat** [arbor-sim/arbor#694]
Some of the documentation is stale:
* Update installation guide (this is just ticket #669).
* Update context API documentation.
* Update recipe and domain decomposition documentation to account for gap junctions.

**Comment by bcumming** [comment]
The documentation for execution contexts, determining the number of threads and GPUs available are out of date, because the functionality for querying resources availability was moved into the libarborenv.

I propose updating the documentation for the hardware querying and wrangling, and move it into a separate page to the domain decomposition, because they are not the same topic, and introducing the hardware API before domain decomposition means that users have to scroll past a lot of distracting text to get to domain decomposition and load balancing.
