### ISSUE TITLE
Python wrapper: default con'tors

### ISSUE THREAD

**Issue by akuesters** [arbor-sim/arbor#783]
Check necessity of default constructors and their documentation string. 

- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/context.cpp#L97
- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/domain_decomposition.cpp#L57
- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/identifiers.cpp#L24
- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/mpi.cpp#L103
- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/recipe.cpp#L205
- https://github.com/arbor-sim/arbor/blob/66b04c127b20783ad29799d3d7aea49e22df69ec/python/schedule.cpp#L178

**Comment by akuesters** [comment]
Also check if non-default constructors necessary:

https://github.com/arbor-sim/arbor/blob/master/python/cells.cpp#L217

**Comment by thorstenhater** [comment]
- cells.cpp: no, fine.
- recipe.cpp: should have a default ctor, since we call `__super__`
- schedule.cpp: Kind of useless, but ok.
- mpi.cpp: defaults to MPI_COMM_WORLD
- identifiers.cpp: cell_member_type should _not_ default to (0, 0). It doesn't in the current master
- context.cpp: default context is fine.
