### ISSUE TITLE
Better cmake location of the python bindings

### ISSUE THREAD

**Issue by Helveg** [arbor-sim/arbor#958]
In case Arbor's bindings are indifferent of Python versions, even towards the future: No problem.

In case they aren't: Is it possible to detect the currently active python interpreter and to place the Python bindings in the site-packages belonging to that interpreter? That would remove the need to add Arbor to the pythonpath, and would go a long way in being compatible with multiple Python versions under pyenv (please support create bindings for every pyenv version :+1: ), Anaconda installations, ...

A different make target/recipe (dunno the right cmake term) that just (re)creates the Python bindings to the active interpreter would also be nice, then I could make a gist for pyenv myself.

**Comment by bcumming** [comment]
Agreed. The current Python build setup is useful only for devs.

This has to work "out of the box" for v0.3 at the end of SGA2

**Comment by bcumming** [comment]
Arbor is Python 3 only. That said, it probably works with Python 2, however we don't test it, and our examples/demos are all Python 3.

**Comment by bcumming** [comment]
I think that PR #97 went some ways towards addressing this. You can provide the python interpreter to CMake as an optional argument (in case it does not automatically detect the correct interpreter), and provide a custom installation path (e.g. the installation path for your virtualenv).

A custom target that will "install only the Python part in a custom path" would break the `configure-build-install` workflow typical of CMake, because to work without requiring installation of the the Arbor C++ library, we would need a custom target, e.g. `make python-install`.

I am working on a `setup.py` that will play nice with `pip3` to present a 'user friendly' installation option.

**Comment by Helveg** [comment]
Ok, but you did mention in that PR that I could just go through the flow again and remake the installation and that it would basically just remake the Python part. If so that is also fine, I can just use a script to install it in all the venvs/versions I want it in.
